export const params = {
  popup: ".popup",
  placeTemplate: ".place-template",
  placesList: document.querySelector(".places"),
  popupZoom: document.querySelector(".popup-zoom"),
  zoomImage: document.querySelector(".popup-zoom__image"),
  zoomCaption: document.querySelector(".popup-zoom__caption"),
  formEditProfile: ".popup_edit-profile",
  formAddPlace: ".popup_add-place",
  formSelector: ".popup__container",
  inputSelector: ".popup__input",
  submitButtonSelector: ".popup__save-btn",
  placeNameInput: document.querySelector(".popup__input_name-place"),
  placeLinkInput: document.querySelector(".popup__input_link-place"),
  inactiveButtonClass: "popup__save-btn_inactive",
  activeErrorClass: "popup__input-error_active",
  inputInvalidClass: "popup__input_invalid",
};
